using Microsoft.EntityFrameworkCore.Migrations;

namespace ReadABit.Infrastructure.Migrations
{
    public partial class RemoveAutoGeneratedId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_WordFamiliarities_UserId",
                table: "WordFamiliarities");

            migrationBuilder.DropIndex(
                name: "IX_WordDefinitions_UserId",
                table: "WordDefinitions");

            migrationBuilder.CreateIndex(
                name: "IX_WordFamiliarities_UserId_WordId",
                table: "WordFamiliarities",
                columns: new[] { "UserId", "WordId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_WordDefinitions_UserId_WordId",
                table: "WordDefinitions",
                columns: new[] { "UserId", "WordId" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_WordFamiliarities_UserId_WordId",
                table: "WordFamiliarities");

            migrationBuilder.DropIndex(
                name: "IX_WordDefinitions_UserId_WordId",
                table: "WordDefinitions");

            migrationBuilder.CreateIndex(
                name: "IX_WordFamiliarities_UserId",
                table: "WordFamiliarities",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_WordDefinitions_UserId",
                table: "WordDefinitions",
                column: "UserId");
        }
    }
}
